 const tiposEs = {
    bug: "bicho",
    dark: "siniestro",
    dragon: "dragón",
    electric: "eléctrico",
    fairy: "hada",
    fighting: "lucha",
    fire: "fuego",
    flying: "volador",
    ghost: "fantasma",
    grass: "planta",
    ground: "tierra",
    ice: "hielo",
    normal: "normal",
    poison: "veneno",
    psychic: "psiquico",
    rock: "roca",
    steel: "acero",
    water: "agua",
  };
  
  const cssTypes = {
    acero: "#b8b8d0",
    agua: "#6890f0",
    bicho: "#a8b820",
    dragón: "#7038f8",
    eléctrico: "#f8d030",
    fantasma: "#705898",
    fuego: "#f08030",
    hada: "#ee99ac",
    hielo: "#98d8d8",
    lucha: "#c03028",
    normal: "#a8a878",
    planta: "#78c850",
    psiquico: "#f85888",
    roca: "#b8a038",
    siniestro: "#705848",
    tierra: "#e0c068",
    veneno: "#a040a0",
    volador: "#a890f0",
  };
export {tiposEs, cssTypes}